services:
    postgres:
        container_name: postgres
        image: postgres:16.4-alpine
        restart: unless-stopped
        command: ["postgres", "-p", "${DB_PORT}"]
        ports:
            - '127.0.0.1:${DB_PORT}:5432'
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./data/db_data:/var/lib/postgresql/data
    nats:
        image: nats-streaming:0.25.6-alpine3.18
        ports:
            - "127.0.0.1:4222:4222"
            - "8222:8222"
        command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
        networks: ["nats"]

networks:
    nats:
        name: nats